Locale: "en-US"
highrailspeed: "3"
overworld: "world"
disable-auto-updater: false
replace-when-server-stops: true
update-branch: ALL
#Valid: ALL, STABLE, DEVELOPMENT
space-travel-need-perm: false
clay-air-lock-block-texture: IRON_BLOCK