name: ClayTech
main: cn.claycoffee.ClayTech.ClayTech
version: 1.2.10
api-version: 1.13
author: ClayCoffee
loadbefore: [Multiverse-Core]
depend: [CS-CoreLib, Slimefun]
commands:
  claytech:
    description: '粘土科技'
    permission: claytech.basic
permissions:
  claytech.basic:
    description: 'Basic command.'
    default: true
  claytech.checkupdate:
    description: 'check update'
    default: op
  claytech.bypasstpcheck:
    description: 'bypass planet tp check'
    default: op